# Copyright (c) 2018, 2020, Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

{{- if eq .Values.type "TRAEFIK" }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.wlsDomain.domainUID }}-traefik
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: '{{ .Values.traefik.hostname }}'
      http:
        paths:
        - path: /console
          backend:
            serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            servicePort: {{ .Values.wlsDomain.adminServerPort }}
        - path: /em
          backend:
            serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            servicePort: {{ .Values.wlsDomain.adminServerPort }}
        - path: /servicebus
          backend:
            serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            servicePort: {{ .Values.wlsDomain.adminServerPort }}
        - path: /lwpfconsole
          backend:
            serviceName: '{{ .Values.wlsDomain.domainUID }}-{{ .Values.wlsDomain.adminServerName | lower | replace "_" "-" }}'
            servicePort: {{ .Values.wlsDomain.adminServerPort }}
        - path:
          backend:
            serviceName: '{{ .Values.wlsDomain.domainUID }}-cluster-{{ .Values.wlsDomain.soaClusterName | lower | replace "_" "-" }}'
            servicePort: {{ .Values.wlsDomain.soaManagedServerPort }}
{{- end }}
